image: node:6.10.0

pages:
  script:
  - npm install
  - npm run build --wwwDir "public" --prod
  artifacts:
    paths:
    - public
  cache:
    untracked: true
    paths:
      - node_modules
  only:
  - master
